import type {Metadata} from 'next'
import localFont from 'next/font/local'
import Navbar from '@/components/Navbar'
import './globals.scss'

const pixel = localFont({
  src: './pixels.ttf',
  variable: "--font-pixel"
})
const pixelHeading = localFont({
  src: './pixelHeading.otf',
  variable: "--font-pixel-heading",
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${pixel.variable} ${pixelHeading.variable}`}>
    <body>
    <header>
      <Navbar/>
    </header>
    {children}</body>
    </html>
  );
}
